### ISSUE TITLE
Won't build on Ubuntu 20.04 x64

### ISSUE THREAD

**Issue by burner1024** [grepwood/libacm#4]
Hi.
Here's the log:
```
make  all-recursive
make[1]: se entra en el directorio '/home/user/Descargas/libacm'
Making all in src
make[2]: se entra en el directorio '/home/user/Descargas/libacm/src'
  CC       acmtool-acmtool.o
acmtool.c:51:14: warning: no previous prototype for ‘libacm_strerror’ [-Wmissing-prototypes]
   51 | const char * libacm_strerror(int err)
      |              ^~~~~~~~~~~~~~~
acmtool.c:262:8: warning: no previous prototype for ‘libacm_decode_file_to_mem’ [-Wmissing-prototypes]
  262 | char * libacm_decode_file_to_mem(const char *fn, uint8_t cf_force_chans, uint32_t * wavsize) {
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~
  CC       decode.lo
  CC       util.lo
  CCLD     libacm.la
  CCLD     acmtool
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/Scrt1.o: in function `_start':
(.text+0x24): undefined reference to `main'
collect2: error: ld returned 1 exit status
```

The [original](https://github.com/markokr/libacm) 1.2 does build.

On an unrelated note, do you have any plans to add conversion from wav to acm, by chance?

**Comment by grepwood** [comment]
Oh my. I haven't touched this in 5 years. I only ever cared it built on Gentoo as a library rather than a program that can be used on its own. I needed this for FreeRadical, but career got in my way.

To answer your other question, I never planned to add an ACM encoder. FreeRadical was meant to support everything that FFmpeg can decode, and as a planned de facto Fallout 1/2 engine, there was no need to support legacy format encoders - only decoders.

**Comment by burner1024** [comment]
oh, I see

**Comment by grepwood** [comment]
One thing you might want to take into consideration is my commit that lets you force the decoder to treat an ACM stream as mono or stereo depending on your choice. Fallout 1 has corrupted ACM files that identify themselves as stereo, but they are in fact mono. If you decode them while respecting their headers, you will get 2x sped up files.
